package me.matl114.hacks.modules.render;

import java.util.HashMap;
import me.matl114.utils.ItemStackUtils;
import net.minecraft.item.ItemStack;

class RenderSubHelperRX extends HashMap<String, ItemStack> {
   RenderSubHelperRX() {
      this.put("bbccddffSSWW", ItemStackUtils.newItem("blackstone", null));
      this.put("bbccddffSSww", ItemStackUtils.newItem("end_stone", null));
      this.put("BBCCddffssWW", ItemStackUtils.newItem("redstone", null));
      this.put("BBCCddffssww", ItemStackUtils.newItem("glowstone_dust", null));
      this.put("bbCCDDFFssWW", ItemStackUtils.newItem("sugar", null));
      this.put("bbCCDDFFssww", ItemStackUtils.newItem("cake", null));
      this.put("BBCCDDffSSWW", ItemStackUtils.newItem("flint", null));
      this.put("BBCCDDffSSww", ItemStackUtils.newItem("kelp", null));
      this.put("bbccddffssWW", ItemStackUtils.newItem("diamond", null));
      this.put("bbccddffssww", ItemStackUtils.newItem("netherite_ingot", null));
      this.put("bbccDDffSSWW", ItemStackUtils.newItem("netherrack", null));
      this.put("bbccDDffSSww", ItemStackUtils.newItem("quartz", null));
      this.put("BBCCDDffssWW", ItemStackUtils.newItem("gunpowder", null));
      this.put("BBCCDDffssww", ItemStackUtils.newItem("gunpowder", "LEAD_DUST"));
      this.put("BBCCddFFSSWW", ItemStackUtils.newItem("dirt", null));
      this.put("BBCCddFFSSww", ItemStackUtils.newItem("oak_log", null));
      this.put("BBccddFFssWW", ItemStackUtils.newItem("glowstone_dust", "COPPER_DUST"));
      this.put("BBccddFFssww", ItemStackUtils.newItem("nether_wart", null));
      this.put("bbCCDDffssWW", ItemStackUtils.newItem("sugar", "SILVER_DUST"));
      this.put("bbCCDDffssww", ItemStackUtils.newItem("phantom_membrane", null));
      this.put("bbCCddFFSSWW", ItemStackUtils.newItem("string", null));
      this.put("bbCCddFFSSww", ItemStackUtils.newItem("glowstone_dust", "GOLD_DUST"));
      this.put("BBccDDFFSSWW", ItemStackUtils.newItem("cobblestone", null));
      this.put("BBccDDFFSSww", ItemStackUtils.newItem("ice", null));
      this.put("bbCCddFFssWW", ItemStackUtils.newItem("gunpowder", "IRON_DUST"));
      this.put("bbCCddFFssww", ItemStackUtils.newItem("ender_pearl", null));
      this.put("BBCCddffSSWW", ItemStackUtils.newItem("granite", null));
      this.put("BBCCddffSSww", ItemStackUtils.newItem("cactus", null));
      this.put("BBccDDFFssWW", ItemStackUtils.newItem("gravel", null));
      this.put("BBccDDFFssww", ItemStackUtils.newItem("snowball", null));
      this.put("bbCCDDFFSSWW", ItemStackUtils.newItem("bone", null));
      this.put("bbCCDDFFSSww", ItemStackUtils.newItem("sponge", null));
      this.put("BBccddffssWW", ItemStackUtils.newItem("glowstone_dust", "SULFATE"));
      this.put("BBccddffssww", ItemStackUtils.newItem("emerald", null));
      this.put("bbCCddffSSWW", ItemStackUtils.newItem("iron_ingot", null));
      this.put("bbCCddffSSww", ItemStackUtils.newItem("basalt", null));
      this.put("bbccDDFFssWW", ItemStackUtils.newItem("glass", null));
      this.put("bbccDDFFssww", ItemStackUtils.newItem("soul_sand", null));
      this.put("BBccDDffSSWW", ItemStackUtils.newItem("andesite", null));
      this.put("BBccDDffSSww", ItemStackUtils.newItem("sugar", "TIN_DUST"));
      this.put("bbCCddffssWW", ItemStackUtils.newItem("ghast_tear", null));
      this.put("bbCCddffssww", ItemStackUtils.newItem("experience_bottle", null));
      this.put("BBccDDffssWW", ItemStackUtils.newItem("strider_spawn_egg", "GCE_LAVA_EGG"));
      this.put("BBccDDffssww", ItemStackUtils.newItem("magma_cream", null));
      this.put("BBccddFFSSWW", ItemStackUtils.newItem("diorite", null));
      this.put("BBccddFFSSww", ItemStackUtils.newItem("sugar", "MAGNESIUM_DUST"));
      this.put("bbCCDDffSSWW", ItemStackUtils.newItem("leather", null));
      this.put("bbCCDDffSSww", ItemStackUtils.newItem("sugar", "ZINC_DUST"));
      this.put("bbccDDffssWW", ItemStackUtils.newItem("blaze_rod", null));
      this.put("bbccDDffssww", ItemStackUtils.newItem("prismarine_shard", null));
      this.put("bbccddFFSSWW", ItemStackUtils.newItem("gold_ingot", null));
      this.put("bbccddFFSSww", ItemStackUtils.newItem("shroomlight", null));
      this.put("BBCCddFFssWW", ItemStackUtils.newItem("clay", null));
      this.put("BBCCddFFssww", ItemStackUtils.newItem("sugar", "ALUMINUM_DUST"));
      this.put("BBCCDDFFSSWW", ItemStackUtils.newItem("feather", null));
      this.put("BBCCDDFFSSww", ItemStackUtils.newItem("turtle_spawn_egg", "GCE_WATER_EGG"));
      this.put("bbccddFFssWW", ItemStackUtils.newItem("soul_soil", null));
      this.put("bbccddFFssww", ItemStackUtils.newItem("prismarine_crystals", null));
      this.put("BBccddffSSWW", ItemStackUtils.newItem("obsidian", null));
      this.put("BBccddffSSww", ItemStackUtils.newItem("crying_obsidian", null));
      this.put("bbccDDFFSSWW", ItemStackUtils.newItem("coal", null));
      this.put("bbccDDFFSSww", ItemStackUtils.newItem("lapis_lazuli", null));
      this.put("BBCCDDFFssWW", ItemStackUtils.newItem("sand", null));
      this.put("BBCCDDFFssww", ItemStackUtils.newItem("slime_ball", null));
   }
}
